### ISSUE TITLE
docker alpine:3.10.1 环境运行报错

### ISSUE THREAD

**Issue by qingbozhang** [yanyiwu/gojieba#86]
docker alpine:3.10.1 环境运行报错，怎解

```text
 
SIGQUIT: quit 
PC=0x47d801 m=4 sigcode=0 
 
goroutine 0 [idle]: 
runtime.futex(0xc000100150, 0x80, 0x0, 0x0, 0x0, 0x0, 0xc000100000, 0x7f5217a3b7e0, 0x7f5217a3b7f0, 0x4153df, ...) 
	/usr/local/go/src/runtime/sys_linux_amd64.s:579 +0x21 fp=0x7f5217a3b778 sp=0x7f5217a3b770 pc=0x47d801 
runtime.futexsleep(0xc000100150, 0x0, 0xffffffffffffffff) 
	/usr/local/go/src/runtime/os_linux.go:44 +0x46 fp=0x7f5217a3b7c8 sp=0x7f5217a3b778 pc=0x43d1c6 
runtime.notesleep(0xc000100150) 
	/usr/local/go/src/runtime/lock_futex.go:159 +0x9f fp=0x7f5217a3b800 sp=0x7f5217a3b7c8 pc=0x4153df 
runtime.mPark() 
	/usr/local/go/src/runtime/proc.go:1340 +0x39 fp=0x7f5217a3b820 sp=0x7f5217a3b800 pc=0x446ab9 
runtime.stopm() 
	/usr/local/go/src/runtime/proc.go:2257 +0x92 fp=0x7f5217a3b848 sp=0x7f5217a3b820 pc=0x4480b2 
runtime.findrunnable(0xc000095000, 0x0) 
	/usr/local/go/src/runtime/proc.go:2916 +0x72e fp=0x7f5217a3b970 sp=0x7f5217a3b848 pc=0x4495ee 
runtime.schedule() 
	/usr/local/go/src/runtime/proc.go:3125 +0x2d7 fp=0x7f5217a3b9d8 sp=0x7f5217a3b970 pc=0x44a937 
runtime.park_m(0xc000103380) 
	/usr/local/go/src/runtime/proc.go:3274 +0x9d fp=0x7f5217a3ba08 sp=0x7f5217a3b9d8 pc=0x44aebd 
runtime.mcall(0x20000) 
	/usr/local/go/src/runtime/asm_amd64.s:327 +0x5b fp=0x7f5217a3ba18 sp=0x7f5217a3ba08 pc=0x479b3b 
rax    0xca 
rbx    0xc000100000 
rcx    0xffffffffffffffff 
rdx    0x0 
rdi    0xc000100150 
rsi    0x80 
rbp    0x7f5217a3b7b8 
rsp    0x7f5217a3b770 
r8     0x0 
r9     0x0 
r10    0x0 
r11    0x286 
r12    0x0 
r13    0x2 
r14    0x22ffed6 
r15    0x0 
rip    0x47d801 
rflags 0x286 
cs     0x33 
fs     0x0 
gs     0x0 
 

```

**Comment by jmt99** [comment]
同问

**Comment by hungtcs** [comment]
+1，我是打包成功以后，运行报错：cannot execute: required file not found

**Comment by karlhuang95** [comment]
还没解决方法吗

**Comment by karlhuang95** [comment]
是不是需要在运行环境安装c++相关软件包呀
